I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat_ldoelh.rpy", line 146, in script
    $ MalChanceuxQuandBlessure()
ScriptError: could not find label 'numero109'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "game/combat_ldoelh.rpy", line 146, in script
    $ MalChanceuxQuandBlessure()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'numero109'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
L'épée du samouraï 1.0
Tue Nov 17 21:32:23 2020
